<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../css/madre.css">
    <body class="back2">
      <?php include '../botonBack.html'; ?>
      <div class="pagina">
        <br>
        <?php include 'h2.html'; ?>
        <br>
        <?php include '../barra.html'; ?>
        <p id="parrafo">
          <br>
          <span class="italic" style="background:#e6e6ff;padding:5px 8px;;border-radius:8px;">pág. 6</span><br>
          Ahora bien, hasta aquí ya podemos conceptuar <a href="../imagenes2.php?ac=13" target="_blank">Dogma Central de la Biología</a>... que ya no es un dogma, sino un <b>principio biológico</b> comprobado; y además <b>preguntarnos</b> acerca de la <b>relación entre éste y la evolución de los seres vivos</b> en la diversidad de especies existentes. Y para ello tenemos como ejemplo el <b>primer ser vivo</b> en la Tierra (<b>procariota heterótrofo</b>)... <span class="marr2">¿cómo podemos explicar su evolución a procariota fotosintético anoxigénico...; y posteriormente a procariota fotosintético oxigénico...?</span>; y <span class="marr2">¿estos tres seres vivos primitivos tendrían el mismo ADN; es decir, los mismos e idénticos genes (genoma)?</span>; y entonces <span class="marr2">¿por qué razón uno de ellos era heterótrofo, el otro realizaba fotosíntesis anoxigénica, y el último, fotosíntesis oxigénica...?</span>. Imaginemos por un instante que una <b>secuencia de nucleótidos</b> localizada (<span class="azul">gen</span>) del <span class="azul">ADN</span> de uno de estos <b>seres vivos primitivos procariotas, codificaba</b> la información que <b>mandataba</b> a la célula (ser vivo) a realizar <b>fotosíntesis anoxigénica</b>; pero con el pasar del tiempo, se produjo un <b>cambio (sustitución</b> de una base nitrogenada por otra, o <b>destrucción</b> de alguna de ellas) en un <span class="ver1">triplete codón</span> de esa <b>primitiva</b> secuencua de nucleótidos, y por lo tanto una <b>variación</b> en el <span class="azul">gen</span> encargado de ejecutar la mencionada <b>"orden"</b>; entonces la pregunta es: <span class="marr2">¿ese gen alterado en uno de sus nucleótidos, a partir de ese momento codifica la realización de fotosíntesis anoxigénica; o el mensaje ya cambió...; es otra "orden" la que debe ejecutar desde ahora en adelante...?</span>. Y la respuesta es... Una vez que el <span class="azul">gen</span> sufre una <a href="../imagenes2.php?ac=14" target="_blank">mutación génica</a> <b>altera su información codificada y mandata</b> a la célula procariota (ser vivo) a realizar <b>otra</b> función (<b>fotosíntesis oxigénica</b>)<b>distinta</b> a la previa a la alteración de la <b>secuencia de nucleótidos</b> (<span class="azul">gen</span>) original. Estos cambios (<b>mutaciones</b>) acontecen al <b>azar</b>, y son <b>previos a la evolución del ser vivo</b>; es decir, <b>primero se muta el <span class="azul">ADN (genoma)</span></b> y luego <b>evoluciona</b> el ser vivo a una <b>nueva especie</b>; a un <span class="azul">genoma</span> distinto construido con el <b>único <span class="ver1">código genético</span> (universal)</b>.
          Y son los agentes <b>físicos</b> (radiaciones, temperatura, humedad, presión, etc) y <b>químicos</b> (componentes de la biosfera, tóxicos, fármacos, alimentos, etc) que <b>producen las mutaciones en forma constante y diferidas en los tiempos de la evolución (millones de años).</b><br><br>
          Ahora bien... como ya fue conceptuado... hoy sabemos (la ciencia) que con posterioridad a la procariota fotosintética oxigénica, las formas de vida en la Tierra evolucionaron a <b>eucariotas</b> vegetales y animales; por lo tanto para el próximo análisis... vamos a centrarnos en esta última; y dentro de la estructura de la misma (eucariota), hagamos un enfoque sobre el <b>núcleo</b>. Es allí <b>únicamente dónde se localiza</b> la denominada <b><span class="azul">cromatina</span></b> (los ácidos nucleicos); la que puede encontrarse en <a href="../imagenes2.php?ac=15" target="_blank">2 formas</a>: desentollada (<span class="azul">eucromatina</span>) y compactada leve/moderada (<span class="azul">heterocromatina</span>) o al máximo (<span class="azul">cromosomas</span>). Y esto nos lleva a la siguiente pregunta... <span class="marr2">¿qué relación existe, si es que existe, entre los 2 estados posibles de la cromatina dentro del núcleo y los flujos de la información (Dogma Central de la Biología) codificada en el ADN del mismo?</span>; es decir <span class="marr2">¿en qué estado está o debe estar la cromatina para que la célula transcriba, traduzca, y/o replique su información codificada en sus genes (genoma)?</span>. Y la respuesta es... la <b>célula</b> transcribe, traduce y/o replica su <span class="azul">ADN</span> <b>únicamente</b> en aquellos sectores del mismo que se encuentra en estado de <span class="azul">eucromatina</span> (cromatina <b>desenrollada</b>) y cómo es lógico pensar... <b>nunca</b> en estado de <span class="azul">heterocromatina</span> (<b>compactación leve/moderada</b>) o <span class="azul">cromosomas</span> (<b>máximo de compactación</b>); baste <b>recordar</b> los procesos de <b>transcripción, traducción, y/o replicación del <span class="azul">ADN</span></b>; es decir, el <b>Dogma Central de la Biología</b>, para deducir este concepto actual.
        </p>
        <br>
        <?php include 'menu2.html'; ?>
        <br><br>
      </div>
    </body>
  </html>
